---
apiVersion: v1
data:
  endpoints.json: |
    {
        "cna": "https://vettom.github.io/api/cna.json",
        "pis": "https://vettom.github.io/api/pis.json"
    }
kind: ConfigMap
metadata:
  name: endpoints
  namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: prom-sd-shim
  labels:
    run: prom-sd-shim
spec:
  containers:
  - name: prom-sd-shim
    image: dennysv/prom_sd_shim:0.1.3
    readinessProbe:
      httpGet:
        path: /
        port: 8080
        scheme: HTTP
    ports:
    - containerPort: 8080
    volumeMounts:
      - name: endpoints-cm
        mountPath: /config
    resources: {}
  volumes:
  - name: endpoints-cm
    configMap:
      name: endpoints
---
