---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: podmonitoring
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list","get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: podsmonitoring-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: monitoring
roleRef:
  kind: ClusterRole
  name: podmonitoring
  apiGroup: rbac.authorization.k8s.io
---