---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{.Values.app.name}}
  name: {{.Values.app.name}}
  namespace: monitoring
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{.Values.app.name}}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{.Values.app.name}}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag}}"
      # - image: dennysv/podmitor_arm:latest
        name: podmonitor-arm-n5l8p
        ports:
        - containerPort: {{.Values.service.port}}
        resources: {}
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 5
          httpGet:
            path: podmon-svc.monitoring.svc.cluster.local:8000/container-resources?pod-label=app.kubernetes.io%2Fcomponent%3Dtesting
            port: 5000
status: {}